# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3
from deutschland.bundestag import api_client, configuration, schemas
from deutschland.bundestag.paths.xml_v2_ausschuesse_index_xml import get  # noqa: E501

from deutschland import bundestag

from .. import ApiTestMixin


class TestXmlV2AusschuesseIndexXml(ApiTestMixin, unittest.TestCase):
    """
    XmlV2AusschuesseIndexXml unit test stubs
        Übersicht über die Ausschüsse  # noqa: E501
    """

    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200


if __name__ == "__main__":
    unittest.main()
