# coding: utf-8

"""
    Bundestag: Live Informationen

    Bundestag Informationen API   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

from deutschland.bundestag.paths.blueprint_servlet_content_article_id_as_app_v2_newsarticle_xml.get import (
    BlueprintServletContentArticleidasAppV2NewsarticleXmlGet,
)
from deutschland.bundestag.paths.iptv_player_macros__x_s_144277506_bttv_mobile_feed_vod_xml.get import (
    IptvPlayerMacrosXs144277506BttvMobileFeedVodXmlGet,
)
from deutschland.bundestag.paths.static_appdata_plenum_v2_conferences_xml.get import (
    StaticAppdataPlenumV2ConferencesXmlGet,
)
from deutschland.bundestag.paths.static_appdata_plenum_v2_speaker_xml.get import (
    StaticAppdataPlenumV2SpeakerXmlGet,
)
from deutschland.bundestag.paths.xml_v2_ausschuesse_ausschuss_id_xml.get import (
    XmlV2AusschuesseAusschussidXmlGet,
)
from deutschland.bundestag.paths.xml_v2_ausschuesse_index_xml.get import (
    XmlV2AusschuesseIndexXmlGet,
)
from deutschland.bundestag.paths.xml_v2_mdb_biografien_mdb_id_xml.get import (
    XmlV2MdbBiografienMdbidXmlGet,
)
from deutschland.bundestag.paths.xml_v2_mdb_index_xml.get import XmlV2MdbIndexXmlGet


class DefaultApi(
    BlueprintServletContentArticleidasAppV2NewsarticleXmlGet,
    IptvPlayerMacrosXs144277506BttvMobileFeedVodXmlGet,
    StaticAppdataPlenumV2ConferencesXmlGet,
    StaticAppdataPlenumV2SpeakerXmlGet,
    XmlV2AusschuesseAusschussidXmlGet,
    XmlV2AusschuesseIndexXmlGet,
    XmlV2MdbBiografienMdbidXmlGet,
    XmlV2MdbIndexXmlGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
